<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "signal_membership".
 *
 * @property integer $id
 * @property integer $sig_id
 * @property integer $mbr_id
 *
 * @property \backend\models\Membership $mbr
 * @property \backend\models\Signal $sig
 * @property string $aliasModel
 */
abstract class SignalMembership extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'signal_membership';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sig_id', 'mbr_id'], 'required'],
            [['sig_id', 'mbr_id'], 'integer'],
            [['sig_id', 'mbr_id'], 'unique', 'targetAttribute' => ['sig_id', 'mbr_id']],
            [['mbr_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Membership::className(), 'targetAttribute' => ['mbr_id' => 'id']],
            [['sig_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Signal::className(), 'targetAttribute' => ['sig_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sig_id' => 'Signal',
            'mbr_id' => 'Membership',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMbr()
    {
        return $this->hasOne(\backend\models\Membership::className(), ['id' => 'mbr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSig()
    {
        return $this->hasOne(\backend\models\Signal::className(), ['id' => 'sig_id']);
    }




}
