<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "usersignal".
 *
 * @property integer $id
 * @property integer $usgusr_id
 * @property integer $usgubt_id
 * @property string $usg_name
 * @property string $usg_emailtoken
 * @property string $usg_pair
 * @property string $usg_remarks
 * @property integer $usg_lock
 * @property string $usg_createdt
 * @property string $usg_updatedt
 * @property integer $usg_deletedat
 * @property string $usg_deletedt
 * @property integer $usgusr_deleted_id
 * @property integer $usg_createdat
 * @property integer $usgusr_created_id
 * @property integer $usg_updatedat
 * @property integer $usgusr_updated_id
 *
 * @property \backend\models\Userbot $usgubt
 * @property \backend\models\User $usgusr
 * @property \backend\models\User $usgusrCreated
 * @property \backend\models\User $usgusrDeleted
 * @property \backend\models\User $usgusrUpdated
 * @property string $aliasModel
 */
abstract class Usersignal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usersignal';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'usgusr_created_id',
                'updatedByAttribute' => 'usgusr_updated_id',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'usg_createdat',
                'updatedAtAttribute' => 'usg_updatedat',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['usgusr_id', 'usgubt_id', 'usg_name', 'usg_emailtoken', 'usg_pair', 'usg_createdt', 'usg_updatedt'], 'required'],
            [['usgusr_id', 'usgubt_id', 'usg_lock', 'usg_deletedat', 'usgusr_deleted_id'], 'integer'],
            [['usg_remarks'], 'string'],
            [['usg_createdt', 'usg_updatedt', 'usg_deletedt'], 'safe'],
            [['usg_name', 'usg_pair'], 'string', 'max' => 32],
            [['usg_emailtoken'], 'string', 'max' => 64],
            [['usgubt_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Userbot::className(), 'targetAttribute' => ['usgubt_id' => 'id']],
            [['usgusr_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['usgusr_id' => 'id']],
            [['usgusr_created_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['usgusr_created_id' => 'id']],
            [['usgusr_deleted_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['usgusr_deleted_id' => 'id']],
            [['usgusr_updated_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['usgusr_updated_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'usgusr_id' => Yii::t('models', 'User'),
            'usgubt_id' => Yii::t('models', 'Userbot'),
            'usg_name' => Yii::t('models', 'Name'),
            'usg_emailtoken' => Yii::t('models', 'Emailtoken'),
            'usg_pair' => Yii::t('models', 'Pair'),
            'usg_remarks' => Yii::t('models', 'Remarks'),
            'usg_lock' => Yii::t('models', 'Lock'),
            'usg_createdat' => Yii::t('models', 'CreatedAt'),
            'usg_createdt' => Yii::t('models', 'Created'),
            'usgusr_created_id' => Yii::t('models', 'CreatedBy'),
            'usg_updatedat' => Yii::t('models', 'UpdatedAt'),
            'usg_updatedt' => Yii::t('models', 'Updated'),
            'usgusr_updated_id' => Yii::t('models', 'UpdatedBy'),
            'usg_deletedat' => Yii::t('models', 'DeletedAt'),
            'usg_deletedt' => Yii::t('models', 'Deleted'),
            'usgusr_deleted_id' => Yii::t('models', 'DeletedBy'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
        /*    'id' => Yii::t('models', 'ID'),
            'usgusr_id' => Yii::t('models', 'User'),
            'usgubt_id' => Yii::t('models', 'Userbot'),
            'usg_name' => Yii::t('models', 'Name'),
            'usg_emailtoken' => Yii::t('models', 'Emailtoken'),
            'usg_pair' => Yii::t('models', 'Pair'),
            'usg_remarks' => Yii::t('models', 'Remarks'),
            'usg_lock' => Yii::t('models', 'Lock'),
            'usg_createdat' => Yii::t('models', 'CreatedAt'),
            'usg_createdt' => Yii::t('models', 'Created'),
            'usgusr_created_id' => Yii::t('models', 'CreatedBy'),
            'usg_updatedat' => Yii::t('models', 'UpdatedAt'),
            'usg_updatedt' => Yii::t('models', 'Updated'),
            'usgusr_updated_id' => Yii::t('models', 'UpdatedBy'),
            'usg_deletedat' => Yii::t('models', 'DeletedAt'),
            'usg_deletedt' => Yii::t('models', 'Deleted'),
            'usgusr_deleted_id' => Yii::t('models', 'DeletedBy'), */
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsgubt()
    {
        return $this->hasOne(\backend\models\Userbot::className(), ['id' => 'usgubt_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsgusr()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'usgusr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsgusrCreated()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'usgusr_created_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsgusrDeleted()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'usgusr_deleted_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsgusrUpdated()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'usgusr_updated_id']);
    }



    /**
     * @inheritdoc
     * @return \backend\models\UsersignalQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\models\UsersignalQuery(get_called_class());
    }


}
