<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detaild description for each parameter.
 * create files, run: ./yii message backend/config/i18n.php
 */
return [
    'color' => null,
    'interactive' => true,
    'sourcePath' => '@backend', //'@yii',
    'messagePath' => '@common/backend_messages', //'@yii/messages',
    'languages' => ['nl-NL'],
    'translator' => 'Yii::t',
    'sort' => true,
    'overwrite' => true,
    'removeUnused' => true,
    'markUnused' => false,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '@common/frontend_messages',
        '@common/backend_messages',
        '/BaseYii.php',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',
    //'db' => 'db',
    //'sourceMessageTable' => '{{%source_message}}',
    //'messageTable' => '{{%message}}',
    //'catalog' => 'messages',
    'ignoreCategories' => [],
];

