<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '3CBotId' => '3Commas bot ID',
    '3CDealStartJson' => '3Commas Deal start message',
    'Active' => 'Actief',
    'Authkey' => 'Authenticatie key',
    'Bot' => '',
    'Bots' => '',
    'Botsignal' => 'Bot signaal',
    'Botsignals' => 'Bot signalen',
    'Categories' => 'Categoriën',
    'Category' => 'Categorie',
    'Code' => '',
    'CostMonth' => 'Maandkosten',
    'CostSymbol' => 'Kost-munt',
    'Created' => 'Aangemaakt',
    'CreatedAt' => 'Aangemaakt op',
    'CreatedBy' => 'Aangemaakt door',
    'DealStrartJson' => 'Deal start message',
    'Deleted' => 'Verwijderd',
    'DeletedAt' => 'Verwijderd op',
    'DeletedBy' => 'Verwijderd door',
    'Description' => 'Omschrijving',
    'Email' => 'Email',
    'Emailtoken' => 'Emailtoken',
    'Enddate' => 'Einde datum',
    'ID' => '',
    'Lock' => '',
    'Message' => 'Bericht',
    'MoralisId' => 'Moralis ID',
    'Name' => 'Naam',
    'PaidTime' => 'Betaald datum',
    'Pair' => '',
    'Password' => 'Wachtwoord',
    'PasswordHash' => 'Wachtwoordhash',
    'PasswordReset' => 'Wachtwoord herstel',
    'Payamount' => 'Betaal bedrag',
    'Paysymbol' => 'Betaal munt',
    'PriceMonth' => 'Maandbedrag',
    'PriceSymbol' => 'Bedrag munt',
    'Rate' => 'Rate',
    'RateURL' => 'Rate URL',
    'Ratesymbol' => 'Rate munt',
    'Remarks' => 'Opmerkingen',
    'Signal' => 'Signaal',
    'SignalActive' => 'Signaal actief',
    'Signalcode' => 'Signaal code',
    'Signallog' => 'Signaal log',
    'Signallogs' => 'Signaal logs',
    'Signals' => 'Signalen',
    'Startdate' => 'Startdatum',
    'Status' => 'Status',
    'Symbol' => 'Munt',
    'Symbols' => 'Munten',
    'Title' => 'Titel',
    'Type' => 'Type',
    'Updated' => 'Bijgewerkt',
    'UpdatedAt' => 'Bijgewerkt op',
    'UpdatedBy' => 'Bijgewerkt door',
    'User' => 'Gebruiker',
    'Userbot' => 'Gebruiker bot',
    'Userbots' => 'Gebruiker bots',
    'Username' => 'Gebruikersnaam',
    'Userpay' => 'Gebruiker betaling',
    'Userpays' => 'Gebruiker betalingen',
    'Users' => 'Gebruikers',
    'Usersignal' => 'Gebruiker signaal',
    'Usersignals' => 'Gebruiker signalen',
    'VerificationToken' => 'Verificatietoken',
];
