<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '3C Deal Start Message' => '',
    '3CBotId' => '3Commas bot ID',
    'Active' => 'Actief',
    'Auto start/stop (experimental)' => '',
    'Category' => 'Categorie',
    'Choose a name for this bot, ie the same one as your 3Commas bot' => 'Kies een naam voor deze bot, bijvoorbeeld dezelfde als uw 3Commas-bot',
    'Copy the 3Commas bot \'Message for deal start signal\'-field text into this field' => 'Kopieer van je 3Commas bot de tekst van het veld \'Message for deal start signal\' in dit veld',
    'Disable the signal when btc is in extreme downtrend<br>Enable the signal when BTC is neutral or uptrend' => '',
    'Discountcode' => 'Kortingscode',
    'Enddate' => 'Eindedatum',
    'My Name' => 'Mijn naam',
    'Name' => 'Naam',
    'Pay method' => 'Betaal methode',
    'Remarks' => 'Opmerkingen',
    'Roles' => 'Rollen',
    'Startdate' => 'Start datum',
    'Usermember' => 'Abonnee',
];
