<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this item?' => 'Weet je zeker dat je dit item wilt verwijderen?',
    'Attach' => '',
    'BackendBotEdit' => '',
    'BackendBotFull' => '',
    'BackendBotView' => '',
    'BackendBotsEdit' => '',
    'BackendBotsFull' => '',
    'BackendBotsView' => '',
    'BackendBotsignalEdit' => '',
    'BackendBotsignalFull' => '',
    'BackendBotsignalView' => '',
    'BackendCategoriesEdit' => '',
    'BackendCategoriesFull' => '',
    'BackendCategoriesView' => '',
    'BackendCategoryEdit' => '',
    'BackendCategoryFull' => '',
    'BackendCategoryView' => '',
    'BackendCryptoaddressEdit' => '',
    'BackendCryptoaddressFull' => '',
    'BackendCryptoaddressView' => '',
    'BackendMembershipEdit' => '',
    'BackendMembershipFull' => '',
    'BackendMembershipView' => '',
    'BackendPricelistEdit' => '',
    'BackendPricelistFull' => '',
    'BackendPricelistView' => '',
    'BackendSignalEdit' => '',
    'BackendSignalFull' => '',
    'BackendSignalView' => '',
    'BackendSignallogEdit' => '',
    'BackendSignallogFull' => '',
    'BackendSignallogView' => '',
    'BackendSignallogsEdit' => '',
    'BackendSignallogsFull' => '',
    'BackendSignallogsView' => '',
    'BackendSymbolEdit' => '',
    'BackendSymbolFull' => '',
    'BackendSymbolView' => '',
    'BackendUserEdit' => '',
    'BackendUserFull' => '',
    'BackendUserView' => '',
    'BackendUserbotEdit' => '',
    'BackendUserbotFull' => '',
    'BackendUserbotView' => '',
    'BackendUsermemberEdit' => '',
    'BackendUsermemberFull' => '',
    'BackendUsermemberView' => '',
    'BackendUserpaidsEdit' => '',
    'BackendUserpaidsFull' => '',
    'BackendUserpaidsView' => '',
    'BackendUserpayEdit' => '',
    'BackendUserpayFull' => '',
    'BackendUserpayView' => '',
    'BackendUsersignalEdit' => '',
    'BackendUsersignalFull' => '',
    'BackendUsersignalView' => '',
    'BackendUsersignalsEdit' => '',
    'BackendUsersignalsFull' => '',
    'BackendUsersignalsView' => '',
    'Cancel' => 'Annuleer',
    'Check' => '',
    'Copy' => 'Kopieer',
    'Create' => 'Aanmaken',
    'Dcrd' => '',
    'Delete' => 'Verwijder',
    'Details' => '',
    'Edit' => 'Aanpassen',
    'First' => 'Eerste',
    'Full list' => 'Volledige lijst',
    'Last' => 'Laatste',
    'List' => 'Lijst',
    'List All' => 'Lijst alles',
    'New' => 'Nieuw',
    'Relations' => 'Relaties',
    'Reset' => 'Herstel',
    'Save' => 'Bewaar',
    'Search' => 'Zoek',
    'Select' => 'Selecteer',
    'Select...' => 'Selecteer...',
    'Update Discord' => '',
    'View' => 'Bekijk',
];
