<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2FASecret' => '2FA Secret',
    '3C Deal Start Message' => '',
    '3CBotId' => '3Commas bot ID',
    'Active' => 'Actief',
    'Authkey' => '',
    'Auto start/stop (experimental)' => 'Auto start/stop (experimenteel)',
    'Category' => 'Categorie',
    'Choose a name for this bot, ie the same one as your 3Commas bot' => 'Kies een naam voor deze bot, bijvoorbeeld dezelfde als uw 3Commas-bot',
    'Copy the 3Commas bot \'Message for deal start signal\'-field text into this field' => 'Kopieer van je 3Commas bot de tekst van het veld \'Message for deal start signal\' in dit veld',
    'Countrycode' => 'Landcode',
    'Created' => 'Aangemaakt',
    'CreatedAt' => 'Aangemaakt op',
    'CreatedBy' => 'Aangemaakt door',
    'Deleted' => 'Verwijderd',
    'DeletedAt' => 'Verwijderd op',
    'DeletedBy' => 'Verwijderd door',
    'Disable the signal when btc is in extreme downtrend<br>Enable the signal when BTC is neutral or uptrend' => 'Schakel het signaal uit wanneer btc zich in een extreme neerwaartse trend bevindt<br>Schakel het signaal in wanneer BTC neutraal of opwaarts is',
    'DiscordId' => 'ID',
    'DiscordJoinedAt' => 'Aangemeld op',
    'DiscordNick' => 'Nick',
    'DiscordRoles' => 'Rollen',
    'DiscordUsername' => 'Gebruikersnaam',
    'Discountcode' => 'Kortingscode',
    'Email' => '',
    'Enddate' => 'Eindedatum',
    'Firstname' => 'Voornaam',
    'For (crypto) payments via Utrust' => 'Tbv crypto betalingen via Utrust',
    'For (crypto) payments via Utrust: 2 letters ISO-code (ex.: NL)' => 'Tbv crypto betalingen via Utrust: 2 letters ISO-code (bijv.: NL)',
    'ID' => '',
    'Language' => 'Taal',
    'Lastname' => 'Achternaam',
    'Lock' => '',
    'MoralisId' => 'Moralis ID',
    'My Name' => 'Mijn naam',
    'Name' => 'Naam',
    'Password' => 'Wachtwoord',
    'PasswordHash' => 'Wachtwoord hash',
    'PasswordReset' => 'Wachtwoord herstellen',
    'Pay via' => 'Betaal via',
    'Remarks' => 'Opmerkingen',
    'Roles' => 'Rollen',
    'SignalActive' => 'Signaal actief',
    'Site Theme' => 'Site thema',
    'SiteLevel' => 'Sitenivo',
    'Startdate' => 'Start datum',
    'Status' => '',
    'Updated' => 'Gewijzigd',
    'UpdatedAt' => 'Gewijzigd op',
    'UpdatedBy' => 'Gewijzigd door',
    'Usermember' => 'Abonnee',
    'Username' => 'Gebruikersnaam',
    'VerificationToken' => 'Congtroletoken',
];
